project:
  type: website
  output-dir: docs

website:
  title: "test-ojs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    - id: none
      style: "docked"
      background: light
      collapse-level: 2
      contents: posts
      sort:
        - "date desc"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



